### ISSUE TITLE
ACCP-2 Discussion :: WBTC/ETH/AMPL balancer pool

### ISSUE THREAD

**Issue by seldamat** [ampleforth/AIPs#19]
As described in the ACCP, a key missing pairing for the Ampleforth protocol is with the top cryptocurrency - Bitcoin. I propose that we create a public balancer pool equally weighted between AMPL:WBTC:ETH (i.e., what will become known as the holy trinity) with a standard trading fee of 0.3%. I also propose that this pool be considered for geyser incentives.

Some key discussion points may address the proposal to use WBTC instead of renBTC/kBTC/BTC++/crvRenBTC or other tokenized forms of BTC, whether the weightings should be equal, what the trading fees should be, and whether this should be incentivized.

Looking forward to hearing your thoughts.

**Comment by zgirson** [comment]
This is an amazing idea I and would love to see this pool @ Balancer.  I agree w/keeping it to wBTC for simplicity.

**Comment by Agarwal94** [comment]
A much needed pool for AMPL liquidity. A pool with BTC is a very crucial progression step in AMPL's liquidity. Great idea!

**Comment by sonicstate** [comment]
good idea

**Comment by jagtapper** [comment]
Concur with all of the above. This can attract a deluge of liquidity to mature the ecosystem, and the EeFi sector.

**Comment by seldamat** [comment]
Another point of discussion may be regarding how a three asset pool may incur more slippage while the total pool liquidity is low. However, IL should be significantly minimized compared to a 50:50 pool. It may be worthwhile to incentivize this pool to encourage quick growth and low slippage.

**Comment by brandoniles** [comment]
I like the idea of AMPL/BTC liquidity as well, but I'd separate that goal from the 3-asset pool on Balancer.

(There is a WBTC/AMPL pool on Mooniswap, but it doesn't have much traction at the moment. But that understandably has to compete with incentivized pools, so maybe it's not so applicable.)

I think the 3-asset pool is most useful to LPs as a balanced portfolio index. I love the basket of AMPL/BTC/ETH representing the most unique classes of digital currencies, and I also love making it easy to construct a portfolio like that!

For traders, it would likely have higher slippage compared to a more targeted pool though? The risk is that we don't know how much liquidity we'll get yet to offset this. It does round out the offerings on the Balancer platform, though. AMPL/stablecoin on the smart pool, then AMPL/basemonies in this one.

In terms of geyser incentives, I don't think it would have the same "liquidity out/rewards in" ratio. We don't want to incentivize "holding" so much as "helping the ecosystem", so I think incentivizing a portfolio construct would be farther down the priority list.

Anyway, if this pool does take off I think it would definitely help ample. Probably worth a shot.

**Comment by brandoniles** [comment]
Seems like there's general support and I haven't heard from any dissenters.

@seldamat If you create the pool, we'll add this to the orchestrator!

**Comment by zgirson** [comment]
To your point @brandoniles on the basket representing the classes of digital assets, it includes arguably the two most likely assets for institutions and hedge funds to dip their toes into for long positions... and they want risk mitigation.  This three-arm basket as its own asset is not only one of a kind I think, it simultaneously represents the store of value side of BTC and the computing side of ETH while also offering the risk mitigation of the elastic qualities of Ampleforth in one basket.  Then you're on Balancer with smart weights to mitigate IL and it's just such an amazing, risk-adjusted asset that I think it could really be quite popular.

**Comment by jagtapper** [comment]
In order to further incentivize the LP of WBTC, would it be helpful to also allow the staking of sBTC, renBTC, tBTC, and other tokenized versions of BTC with a modest degree of liquidity? 

It could simply be that the other forms of BTC are converted to WBTC on the backend (if such a smart contract function could be written). Or perhaps the kMPL asset backed by the ASDAO could be used in some capacity to facilitate these functions. Various sophisticated methods are likely to emerge. 

This kind of inclusivity, in the long run, could bootstrap liquidity for amplBTC - a BTC backed by AMPL and other elastic assets slated for listing in the upcoming elastic AMM on the roadmap. 

On a related note, the Ampleforth A should become a typeable symbol attached to the AMPL backed BTC.
